config/routes.rb
Rails.application.routes.draw do

  resources :charts do
    get 'random', on: :collection
  end
  resources :tracks do
    get 'without_ilm', on: :collection
    get 'without_occ', on: :collection
    get 'without_tupac', on: :collection
  end

  root 'home#index'

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  has_many :entries, class_name: "ChartEntry", foreign_key: "chart_id"
  default_scope { order(date: :asc) }

  def tupac_page
    "https://production.live.bbc.co.uk/music/charts/radio1/singles/#{date}/publish"
  end

  def official_chart_page
    datestr = official_chart_date.strftime("%Y%m%d")
    "http://www.officialcharts.com/charts/uk-top-40-singles-chart/#{datestr}/750140/"
  end
  
  def official_chart_id
    official_chart_date.strftime("7501-%Y%m%d")
  end

  def official_chart_date
    date+6
  end

  def to_s
    date.to_s
  end
  
  def to_param
    date.to_s
  end
end

app/models/chart_entry.rb
class ChartEntry < ActiveRecord::Base
  belongs_to :chart
  belongs_to :track
  default_scope { order(position: :asc) }
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :entries, class_name: "ChartEntry"

  def tupac_page
    "https://production.live.bbc.co.uk/music/records/#{record_id}"
  end
  
  def ilm_info_page
    "http://desktopjukebox.broadchart.com/bbc/members/asset_info/#{ilm_id.sub('-','/')}"
  end
  
  def ilm_player_page
    (album_id,track_no) = ilm_id.split('-')
    "http://desktopjukebox.broadchart.com/bbc/members/player.cgi?album_id=#{album_id}&track_no=#{track_no}"
  end
  
  def image_url(size='64x64')
    unless attributes['image_url'].blank?
      attributes['image_url'].sub(/\d+x\d+/, size)
    end
  end
  
  def spotify_url
    "https://open.spotify.com/track/#{spotify_id}"
  end
  
  def amazon_url
    "http://www.amazon.co.uk/dp/#{amazon_id}"
  end
  
  def deezer_url
    "http://www.deezer.com/track/#{deezer_id}"
  end
  
  def to_hash
    attributes.to_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  require 'csv'
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
    @chart = Chart.where(:date => params[:id]).
                   includes(:entries => [:track]).first
    @entries = ChartEntry.where(:chart => @chart)
  end

  def random
    @chart = Chart.all.order('RANDOM()').first
    redirect_to @chart
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to charts_path
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
  end
  
  def show
    @track = Track.find(params[:id])
  end
  
  def without_ilm
    @tracks = Track.all.where("ilm_id IS NULL")
    respond_to do |format|
      format.html { render :list }
      format.csv { render :list }
    end
  end

  def without_occ
    @tracks = Track.all.where("occ_product_id IS NULL")
    respond_to do |format|
      format.html { render :list }
      format.csv { render :list }
    end
  end

  def without_tupac
    @tracks = Track.all.where("record_id IS NULL")
    respond_to do |format|
      format.html { render :list }
      format.csv { render :list }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_duration(secs)
    sprintf("%2.2d:%2.2d", secs.div(60), secs % 60)
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charts</h1>

<ul>
  <% @charts.each do |chart| %>
    <li><%= link_to(chart, chart) %></li>
  <% end %>
</ul>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to("Offical Chart Company Page", @chart.official_chart_page) %>
</p>


<table class="table table-condensed chart">
  <thead>
    <tr>
      <th>#</th>
      <th>Artwork</th>
      <th>Artist</th>
      <th>Title</th>
      <th>iLM</th>
      <th>OCC</th>
    </tr>
  </thead>
  
  <tbody class="table-striped">
    <% @entries.each do |entry| %>
      <tr>
        <td class="position"><%= entry.position %></td>
        <td class="image">
          <% unless entry.track.image_url.blank? %>
            <%= link_to(image_tag(entry.track.image_url, size: '64x64'), entry.track.tupac_page) %>
          <% end %>
        </td>
        <td class="artist"><%= entry.track.artist %></td>
        <td class="title"><%= link_to(entry.track.title, entry.track) %></td>
        <td>
        <% unless entry.track.ilm_id.nil? %>
          <%= link_to('▶', entry.track.ilm_player_page, target: '_blank') %>
          <%= link_to(entry.track.ilm_id, entry.track.ilm_info_page, target: '_blank') %>
        <% end %>
        </td>
        <td><%= entry.track.occ_product_id %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Chart Data Analysis</title>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="/bootstrap-3.3.6/css/bootstrap.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Chart Data Analysis</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="/charts">Charts</a></li>
        <li><a href="/tracks">Tracks</a></li>
      </ul>
    </div>
  </nav>

  <div class="container">
  <%= yield %>
  </div>

  <script src="/js/jquery-2.2.4.min.js"></script>
  <script src="/bootstrap-3.3.6/js/bootstrap.min.js"></script>
    
  </body>
</html>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr><th>Total Tracks</th> <td><%= Track.count %></td></tr>
  <tr><th>With iLike Music</th> <td><%= Track.where('ilm_id IS NOT NULL').count %></td></tr>
  <tr><th><%= link_to('Without iLike Music', without_ilm_tracks_path) %></th> <td><%= Track.where('ilm_id IS NULL').count %></td></tr>
  <tr><th><%= link_to('Without OCC Product ID', without_occ_tracks_path) %></th> <td><%= Track.where('occ_product_id IS NULL').count %></td></tr>
  <tr><th><%= link_to('Without Tupac ID', without_tupac_tracks_path) %></th> <td><%= Track.where('record_id IS NULL').count %></td></tr>
</table>

app/views/tracks/list.csv.erb
<%= CSV.generate_line(['Artist', 'Title', 'Record ID']) -%>
<%- @tracks.each do |track| -%>
<%= CSV.generate_line([track.artist, track.title, track.record_id]) -%>
<%- end -%>

app/views/tracks/list.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tracks</h1>

<table class="table">
  <tr>
    <th>Artist</th>
    <th>Title</th>
    <th>Record ID</th>
  </tr>

  <% @tracks.each do |track| %>
    <tr>
      <td><%= track.artist %></td>
      <td><%= link_to(track.title, track) %></td>
      <td><%= link_to(track.record_id, track.tupac_page) %></td>
    </tr>
  <% end %>
</table>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <table class="table">
      <tr><th>Artist</td> <td><%= @track.artist %></td></tr>
      <tr><th>Title</td> <td><%= @track.title %></td></tr>
      <tr><th>BBC Record ID</td> <td><%= link_to(@track.record_id, @track.tupac_page) %></td></tr>
      <tr><th>iLikeMusic ID</td> <td><%= @track.ilm_id.nil? ? 'n/a' : link_to(@track.ilm_id, @track.ilm_info_page, target: '_blank') %></td></tr>
      <tr><th> &nbsp; Duration</td> <td><%= format_duration(@track.ilm_duration) %></td></tr>
      <tr><th> &nbsp; Genre</td> <td><%= @track.ilm_genre %></td></tr>
      <tr><th> &nbsp; ISRC</td> <td><%= @track.ilm_isrc %></td></tr>
      <tr><th> &nbsp; ISWC</td> <td><%= @track.ilm_iswc %></td></tr>
      <tr><th> &nbsp; TuneCode</td> <td><%= @track.ilm_tunecode %></td></tr>
      <tr><th> &nbsp; Year</td> <td><%= @track.ilm_year %></td></tr>
      <tr><th>Official Chart ID</td> <td><%= @track.occ_product_id %></td></tr>
      <tr><th> &nbsp; Label</td> <td><%= @track.label %></td></tr>
      <tr><th> &nbsp; iTunes</td> <td><%= link_to(@track.itunes_url, @track.itunes_url) %></td></tr>
      <tr><th> &nbsp; Spotify</td> <td><%= link_to(@track.spotify_url, @track.spotify_url) %></td></tr>
      <tr><th> &nbsp; Amazon</td> <td><%= link_to(@track.amazon_url, @track.amazon_url) %></td></tr>
      <tr><th> &nbsp; Deezer</td> <td><%= link_to(@track.deezer_url, @track.deezer_url) %></td></tr>
      <tr><th>Updated At</td> <td><%= @track.updated_at %></td></tr>
      <tr><th>Created At</td> <td><%= @track.created_at %></td></tr>
    </table>
  </div>


  <div class="col-md-4">
    <% unless @track.image_url.nil? %>
      <%= image_tag(@track.image_url('400x400'), class: 'img-thumbnail') %>
    <% end %>
  </div>
</div>

<h2>Charts</h2>

<ul>
  <% @track.entries.each do |entry| %>
    <li><%= link_to("#{entry.chart.date} - ##{entry.position}", entry.chart) %></li>
  <% end %>
</ul>